import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {chromium,expect} from '@playwright/test';
import {createGameServer} from '../game/server/index.js';
import {CodexTransport} from '../game/server/harness.js';
import {ATTACK_PP,SPECIES} from '../game/shared/model.js';
import {sceneObjects} from '../game/shared/scene.js';
import {BrowserGame} from './browser-game.js';

const original=CodexTransport.prototype.connect;let cliAttempts=0;
CodexTransport.prototype.connect=async function(){cliAttempts++;throw new Error('Preview test may not connect Codex.');};
const app=await createGameServer({dataDir:resolve('.test-data','battle-'+randomUUID()),port:0,adminPort:0,host:'127.0.0.1',fixture:false});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:960},reducedMotion:'no-preference'});
const errors:string[]=[],checks:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const output=resolve('.test-data/verification');mkdirSync(output,{recursive:true});
try{
  await page.goto('http://127.0.0.1:'+app.adminPort);await page.getByRole('button',{name:'Single player',exact:true}).click();await page.getByRole('button',{name:'Play tutorial preview'}).click();
  await page.getByRole('button',{name:'Skip introduction'}).click();await page.getByRole('dialog',{name:'Choose your first companion'}).getByRole('button',{name:/Bulbasaur/}).click();await page.getByRole('dialog',{name:'A friendship begins'}).getByRole('button',{name:/Continue/}).click();
  const child=[...app.previewChildren][0],player=()=>child.store.players()[0],driver=new BrowserGame(page,player,id=>child.store.region(id));
  const geometry=child.store.regions().map(r=>createHash('sha256').update(JSON.stringify(r.tiles)).digest('hex'));
  assert.equal(new Set(geometry).size,5);checks.push('Five prepared maps have five distinct tile layouts.');
  const guide=driver.object('guide');await driver.face(guide);
  const position={x:player().x,y:player().y};
  await page.keyboard.down({north:'ArrowUp',south:'ArrowDown',west:'ArrowLeft',east:'ArrowRight'}[player().facing]);
  await page.waitForTimeout(220);
  await page.keyboard.up({north:'ArrowUp',south:'ArrowDown',west:'ArrowLeft',east:'ArrowRight'}[player().facing]);
  assert.deepEqual({x:player().x,y:player().y},position);
  await driver.settle();await page.getByRole('button',{name:'Interact',exact:true}).click();await driver.continue();assert.equal(player().tutorial,1);
  checks.push('Facing-adjacent guide interaction works and walking into the guide does not move through the NPC.');
  await driver.travel('north','0,-1');
  await driver.interact(driver.object('guide'));
  await page.getByRole('dialog').getByRole('button',{name:/Practice battle/}).click();
  await expect(page.locator('.encounter-transition')).toHaveAttribute('data-encounter-phase','closing');
  await expect(page.locator('.gba-battle')).toHaveCount(0);
  const encounterSteps=player().steps;
  await page.keyboard.press('ArrowRight');
  assert.equal(player().steps,encounterSteps,'Movement stays locked during the encounter wipe.');
  await page.waitForTimeout(520);
  await page.screenshot({path:resolve(output,'encounter-wipe.png'),fullPage:true});
  await expect(page.locator('.encounter-transition')).toHaveAttribute('data-encounter-phase','revealing');
  await expect(page.getByRole('button',{name:'FIGHT',exact:true,includeHidden:true})).toBeDisabled();
  await driver.readyBattle();
  await expect(page.locator('.encounter-transition')).toHaveCount(0);
  checks.push('Encounter flashes and closes over the map before revealing battle; movement and battle commands remain locked until the reveal finishes.');
  const before=structuredClone(player()),enemyBefore=before.battle!.enemy.hp;
  await page.evaluate(`window.battleSamples=[];window.battleObserver=new MutationObserver(function(){const root=document.querySelector('.gba-battle');if(!root)return;window.battleSamples.push({phase:root.dataset.battlePhase,player:Number(root.querySelector('.gba-health[data-side="player"]').dataset.displayedHp),enemy:Number(root.querySelector('.gba-health[data-side="enemy"]').dataset.displayedHp),text:root.querySelector('.gba-message')?.textContent||''});});window.battleObserver.observe(document.querySelector('.gba-battle'),{attributes:true,subtree:true,attributeFilter:['data-battle-phase','data-displayed-hp']});`);
  await page.getByRole('button',{name:'FIGHT',exact:true}).click();await expect(page.locator('.gba-pp')).toHaveText('PP '+ATTACK_PP+'/'+ATTACK_PP);
  await page.screenshot({path:resolve(output,'battle-moves.png'),fullPage:true});
  await page.getByRole('button',{name:'Tackle',exact:true}).click();await expect.poll(()=>player().battle!.round).toBe(1);await expect(page.getByRole('button',{name:'FIGHT',exact:true})).toBeDisabled();await driver.readyBattle();
  await expect(page.locator('.encounter-transition')).toHaveCount(0);
  const samples=await page.evaluate('window.battleObserver.disconnect(); window.battleSamples') as Array<{phase:string;player:number;enemy:number;text:string}>;
  assert.ok(samples.some(s=>s.phase==='player-attack'));assert.ok(samples.some(s=>s.phase==='enemy-attack'));
  assert.ok(samples.findIndex(s=>s.phase==='player-attack')<samples.findIndex(s=>s.phase==='enemy-attack'));
  const damageFrames=samples.filter(s=>s.enemy<enemyBefore&&s.enemy>player().battle!.enemy.hp);assert.ok(damageFrames.length>0);
  assert.ok(damageFrames.every(s=>s.player===before.party[before.active].hp),'Player HP must not jump during the player attack animation.');
  assert.equal(player().party[player().active].pp!.attack,ATTACK_PP-1);
  await page.screenshot({path:resolve(output,'battle-commands.png'),fullPage:true});
  checks.push('FIGHT opens move selection with real PP; server attack consumes one PP; player attack and counterattack animate sequentially with intermediate HP and locked commands.');
  await page.reload();await page.getByRole('button',{name:'Single player',exact:true}).click();
  await expect(page.locator('.gba-battle')).toBeVisible();
  await expect(page.locator('.encounter-transition')).toHaveCount(0);
  await driver.readyBattle();
  checks.push('Resuming an existing battle does not replay the encounter transition.');
  await page.getByRole('button',{name:'BAG',exact:true}).click();await expect(page.getByRole('button',{name:/POKé BALL/})).toBeVisible();await page.getByRole('button',{name:'CANCEL',exact:true}).click();
  await page.getByRole('button',{name:'POKéMON',exact:true}).click();await expect(page.locator('.gba-party-menu')).toContainText('Bulbasaur');await page.getByRole('button',{name:'CANCEL',exact:true}).click();
  await driver.winBattle();assert.equal(player().tutorial,2);
  const outdoor=driver.scene(),door=sceneObjects(outdoor).find(o=>o.kind==='door'&&o.targetScene==='sanctuary')!;assert.ok(door);
  await driver.goTo(door);assert.equal(player().sceneId,'sanctuary');await page.waitForTimeout(180);
  const healer=driver.object('healer');await driver.interact(healer);await driver.continue();assert.equal(player().party[0].hp,player().party[0].maxHp);assert.equal(player().party[0].pp!.attack,ATTACK_PP);assert.equal(player().party[0].pp!.special,SPECIES[player().party[0].species].specialPp);
  const pc=driver.object('room-pc');await driver.interact(pc);await expect(page.getByRole('dialog')).toContainText('PC');await driver.continue();
  await page.screenshot({path:resolve(output,'interior-inspection.png'),fullPage:true});
  const exit=sceneObjects(driver.scene()).find(o=>o.kind==='door'&&o.targetScene==='outdoor')!;await driver.goTo(exit);assert.equal(player().sceneId,undefined);await page.waitForTimeout(220);assert.equal(player().sceneId,undefined);
  checks.push('Walking through a door enters the room; adjacent healer restores actual HP and PP; PC inspection works; exit returns outdoors without bouncing back.');
  await page.emulateMedia({reducedMotion:'reduce'});
  await driver.travel('south','0,0');await driver.interact(driver.object('guide'));
  await page.getByRole('dialog').getByRole('button',{name:/Practice catching/}).click();
  await expect(page.locator('.gba-battle')).toBeVisible({timeout:800});
  await expect(page.locator('.encounter-transition')).toHaveCount(0);
  await driver.readyBattle();await driver.runAway();
  checks.push('Reduced motion skips the flash and wipe and enters the battle directly.');
  assert.equal(cliAttempts,0);assert.equal(child.generator.status.used,0);assert.equal(child.store.regions().length,5);assert.deepEqual(errors,[]);
}catch(error){errors.push((error as Error).stack??String(error));process.exitCode=1;await page.screenshot({path:resolve(output,'gameplay-failure.png'),fullPage:true});writeFileSync(resolve(output,'gameplay-failure.html'),await page.content());}
finally{const result={status:process.exitCode?'failed':'passed',cliAttempts,checks,errors};writeFileSync(resolve(output,'battle-interactions.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();await app.close();CodexTransport.prototype.connect=original;}
