import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {chromium,expect} from '@playwright/test';
import {createGameServer} from '../game/server/index.js';
import {CodexTransport} from '../game/server/harness.js';
import {DIRECTIONS,TILE,type Direction} from '../game/shared/model.js';
import {solidAt,sceneObjects} from '../game/shared/scene.js';

const original=CodexTransport.prototype.connect;let cliAttempts=0;
CodexTransport.prototype.connect=async function(){cliAttempts++;throw new Error('Movement preview must not invoke Codex.');};
const app=await createGameServer({dataDir:resolve('.test-data','held-'+randomUUID()),port:0,adminPort:0,host:'127.0.0.1',fixture:false});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'no-preference'});
const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
const result:Record<string,unknown>={status:'running'};
try{
  await page.goto('http://127.0.0.1:'+app.adminPort);
  await page.getByRole('button',{name:'Single player',exact:true}).click();
  await page.getByRole('button',{name:'Play tutorial preview'}).click();
  await page.getByRole('button',{name:'Skip introduction'}).click();
  await page.getByRole('dialog',{name:'Choose your first companion'}).getByRole('button',{name:/Bulbasaur/}).click();
  await page.getByRole('dialog',{name:'A friendship begins'}).getByRole('button',{name:/Continue/}).click();
  const child=[...app.previewChildren][0],player=()=>child.store.players()[0],before=structuredClone(player()),region=child.store.region(before.regionId)!;
  const options=(['east','west','south','north'] as Direction[]).map(direction=>{const [dx,dy]=DIRECTIONS[direction];let free=0;for(let i=1;i<=8;i++){const x=before.x+dx*i,y=before.y+dy*i;if(solidAt(region,x,y)||sceneObjects(region).some(o=>o.kind==='door'&&o.x===x&&o.y===y))break;free++;}return {direction,free};});
  const route=options.find(o=>o.free>=7);assert.ok(route,'Spawn must offer a clear straight route for a one-second hold.');
  const key={east:'d',west:'a',north:'w',south:'s'}[route.direction];
  await expect(page.locator('.game-canvas canvas')).toHaveAttribute('data-moving','false');
  await page.getByRole('button',{name:'Open game menu'}).focus();
  await page.keyboard.down(key);
  const frames=await page.evaluate(`new Promise(done=>{const canvas=document.querySelector('.game-canvas canvas'),start=performance.now(),samples=[];function sample(){const t=performance.now()-start;samples.push({t,x:Number(canvas.dataset.playerX),y:Number(canvas.dataset.playerY),moving:canvas.dataset.moving==='true'});if(t<1000)requestAnimationFrame(sample);else done(samples);}requestAnimationFrame(sample);})`) as Array<{t:number;x:number;y:number;moving:boolean}>;
  await page.keyboard.up(key);
  const end=frames.at(-1)!,axis=route.direction==='east'||route.direction==='west'?'x':'y',origin=before[axis]*TILE;
  const renderedTiles=Math.abs(end[axis]-origin)/TILE;
  const fractional=frames.filter(f=>Math.abs(f[axis]/TILE-Math.round(f[axis]/TILE))>.015);
  assert.ok(renderedTiles>=5.3&&renderedTiles<=7.2,'One held key must move roughly six rendered tiles per second, observed '+renderedTiles);
  assert.ok(fractional.length>=12,'Renderer must expose many intermediate positions, not tile snapping.');
  const sign=DIRECTIONS[route.direction][axis==='x'?0:1];
  for(let i=1;i<frames.length;i++)assert.ok((frames[i][axis]-frames[i-1][axis])*sign>=-.2,'Movement must not snap backward.');
  await expect(page.locator('.game-canvas canvas')).toHaveAttribute('data-moving','false');
  await expect.poll(async()=>Number(await page.locator('.game-canvas canvas').getAttribute('data-player-'+axis))).toBe(player()[axis]*TILE);
  await page.setViewportSize({width:390,height:844});
  const touchDirection={east:'west',west:'east',north:'south',south:'north'}[route.direction] as Direction;
  const touchButton=page.locator('.touch-controls button[data-direction="'+touchDirection+'"]');
  await touchButton.scrollIntoViewIfNeeded();
  const bounds=await touchButton.boundingBox();assert.ok(bounds);
  const touchStart=structuredClone(player());
  const cdp=await page.context().newCDPSession(page);
  await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:bounds.x+bounds.width/2,y:bounds.y+bounds.height/2}]});
  const touchFrames=await page.evaluate(`new Promise(done=>{const canvas=document.querySelector('.game-canvas canvas'),start=performance.now(),samples=[];function sample(){const t=performance.now()-start;samples.push({t,x:Number(canvas.dataset.playerX),y:Number(canvas.dataset.playerY),moving:canvas.dataset.moving==='true'});if(t<1000)requestAnimationFrame(sample);else done(samples);}requestAnimationFrame(sample);})`) as Array<{t:number;x:number;y:number;moving:boolean}>;
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  const touchDistance=Math.abs(touchFrames.at(-1)![axis]-touchStart[axis]*TILE)/TILE;
  assert.ok(touchDistance>=5.3&&touchDistance<=7.2,'One touch hold must continuously move, observed '+touchDistance);
  await expect(page.locator('.game-canvas canvas')).toHaveAttribute('data-moving','false');
  const tapDirection=route.direction,tapSteps=player().steps;
  await page.locator('.touch-controls button[data-direction="'+tapDirection+'"]').click();
  await expect.poll(()=>player().steps).toBe(tapSteps+1);
  await expect(page.locator('.game-canvas canvas')).toHaveAttribute('data-moving','false');
  assert.equal(player().steps,tapSteps+1,'A normal pointer tap must not enqueue a duplicate step.');
  const savedPosition={x:player().x,y:player().y,steps:player().steps};
  await page.getByRole('button',{name:'Open game menu'}).click();
  await page.getByRole('button',{name:'Trainer profile'}).click();
  await page.getByRole('button',{name:'Leave world',exact:true}).click();
  await page.getByRole('button',{name:'Single player',exact:true}).click();
  await expect(page.locator('.game-canvas canvas')).toHaveAttribute('data-moving','false');
  await page.waitForTimeout(400);
  assert.deepEqual({x:player().x,y:player().y,steps:player().steps},savedPosition,'Resuming must not replay a consumed touch request.');
  Object.assign(result,{resumeReplaysInput:false});
  assert.equal(cliAttempts,0);assert.deepEqual(errors,[]);
  Object.assign(result,{status:'passed',direction:route.direction,focusedElement:'Open game menu button',holdMs:end.t,renderedTiles,intermediateFrames:fractional.length,frameCount:frames.length,touch:{direction:touchDirection,renderedTiles:touchDistance,frames:touchFrames.length,singleTapSteps:1},cliAttempts,frames});
}catch(error){Object.assign(result,{status:'failed',error:(error as Error).stack});process.exitCode=1;}
finally{mkdirSync(resolve('.test-data/verification'),{recursive:true});writeFileSync(resolve('.test-data/verification/held-movement.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({...result,frames:undefined},null,2));await browser.close();await app.close();CodexTransport.prototype.connect=original;}
