import {test} from 'node:test';
import assert from 'node:assert/strict';
import {TileMotion,sampleTrajectory} from '../game/client/movement.js';
import {WALK_MS,type MovementState} from '../game/shared/model.js';
function ack(seq:number,toX:number,accepted=true):MovementState{return{seq,fromX:0,fromY:0,toX,toY:0,startedAt:0,duration:WALK_MS,accepted};}
test('walking is linear and frame-rate independent rather than easing toward snapshots',()=>{for(const fps of[30,60,144]){const m=new TileMotion({x:0,y:0});const seq=m.begin({x:1,y:0},0)!;m.acknowledge(ack(seq,1),10);for(let t=0;t<WALK_MS;t+=1000/fps)assert.ok(Math.abs(m.position(t).x-t/WALK_MS)<1e-9);assert.equal(m.position(80).x,.5);assert.equal(m.position(WALK_MS).x,1);}});
test('held input starts the next tile without pause or pullback by an older snapshot',()=>{const m=new TileMotion({x:0,y:0});const seq=m.begin({x:1,y:0},0)!;m.acknowledge(ack(seq,1),30);m.sync({x:0,y:0},0,150);assert.equal(m.position(160).x,1);assert.equal(m.ready(160),true);m.begin({x:2,y:0},160);m.sync({x:1,y:0},1,200);assert.equal(m.position(200).x,1.25);});
test('unacknowledged inputs cannot accumulate and rejection reconciles smoothly',()=>{const m=new TileMotion({x:0,y:0});const seq=m.begin({x:1,y:0},0)!;assert.equal(m.begin({x:2,y:0},200),null);m.acknowledge(ack(seq,0,false),200);assert.equal(m.position(232).x,.5);assert.equal(m.position(264).x,0);assert.equal(m.ready(264),true);});
test('blocked input does not move and stale acknowledgements cannot rewind',()=>{const m=new TileMotion({x:4,y:2},5);const seq=m.begin({x:4,y:2},0,false)!;m.acknowledge({...ack(seq,4,false),toY:2,duration:0},5);m.acknowledge(ack(4,0),15);assert.deepEqual(m.position(20),{x:4,y:2});});
test('remote trajectories clamp endpoints and interpolate evenly',()=>{const m={...ack(1,1),startedAt:100};assert.equal(sampleTrajectory(m,90).x,0);assert.equal(sampleTrajectory(m,180).x,.5);assert.equal(sampleTrajectory(m,400).x,1);});
test('lost feedback recovery never rewinds past the last acknowledged position to a stale snapshot',()=>{const m=new TileMotion({x:0,y:0});const first=m.begin({x:1,y:0},0)!;m.acknowledge(ack(first,1),20);m.begin({x:2,y:0},160);m.sync({x:0,y:0},0,1800);assert.deepEqual(m.position(1800),{x:1,y:0});assert.equal(m.acknowledgedSequence,first);assert.equal(m.ready(1800),true);assert.equal(m.begin({x:2,y:0},1800),3);});
test('a newer authoritative warp supersedes an older prediction immediately',()=>{const m=new TileMotion({x:0,y:0});m.begin({x:1,y:0},0);m.acknowledge({...ack(5,10),duration:0},50);assert.deepEqual(m.position(50),{x:10,y:0});assert.equal(m.ready(50),true);m.acknowledge(ack(1,1),80);assert.deepEqual(m.position(80),{x:10,y:0});});
test('an authoritative warp cancels an in-progress rejection correction',()=>{const m=new TileMotion({x:0,y:0});const seq=m.begin({x:1,y:0},0)!;m.acknowledge({...ack(seq,0,false),duration:0},100);assert.ok(m.position(110).x>0);m.acknowledge({...ack(seq+1,10),duration:0},110);assert.deepEqual(m.position(110),{x:10,y:0});assert.equal(m.ready(110),true);assert.deepEqual(m.position(200),{x:10,y:0});});
test('duplicate snapshot acknowledgements preserve an active rejection correction',()=>{const m=new TileMotion({x:0,y:0});const seq=m.begin({x:1,y:0},0)!;const rejected={...ack(seq,0,false),duration:0};m.acknowledge(rejected,160);m.acknowledge(rejected,176);assert.equal(m.position(192).x,.5);assert.equal(m.position(224).x,0);});
