import {useState} from 'react';
import {creatureInfo,creatureKey,type GameState,type Action} from '../shared/model';
import {TRAITS,type LeaderboardEntry} from '../shared/content';
import {creatureImage,itemImage,vehicleImage} from './content-art';

export type VarietyTab='shop'|'nursery'|'records'|'rides'|'items'|'codex';
export default function VarietyPanels({tab,state,onAction}:{tab:VarietyTab;state:GameState;onAction:(action:Action)=>void}){
  const {me,variety}=state,[targetIndex,setTargetIndex]=useState(state.me.active),[a,setA]=useState(''),[b,setB]=useState(''),[metric,setMetric]=useState<keyof Pick<LeaderboardEntry,'captures'|'species'|'maps'|'tiles'|'trainers'>>('captures');
  if(!variety)return <p>Opening your catalog…</p>;
  const all=[...me.party,...me.storage],quantity=(id:string)=>id==='poke-ball'?me.balls:id==='potion'?me.potions:me.items?.[id]??0;
  if(tab==='shop')return <div className="variety-panel"><p className="wallet">Coins: ₽ {me.coins}</p><p className="small-copy">{variety.npcTraits?`${variety.npcTraits.temperament} · ${variety.npcTraits.interest}. ${variety.npcTraits.quirk}`:''}</p>{!variety.shopOpen?<p>Stand beside a shopkeeper inside a shelter to buy supplies.</p>:null}<div className="catalog-list">{variety.shopItems.map(item=><div className="catalog-row" key={item.id}><img src={itemImage(item)} alt=""/><div><strong>{item.name}</strong><p>{item.description}</p><small>{item.source==='harness'?'Local creation · ':''}Owned: {quantity(item.id)}</small></div><button className="button" disabled={!variety.shopOpen||me.coins<item.price} onClick={()=>onAction({kind:'buyItem',itemId:item.id,quantity:1})}>Buy · ₽{item.price}</button></div>)}{variety.shopVehicles.map(vehicle=><div className="catalog-row" key={vehicle.id}><img src={vehicleImage(vehicle)} alt=""/><div><strong>{vehicle.name}</strong><p>{vehicle.description}</p><small>{vehicle.source==='harness'?'Local design · ':''}{Math.round(160/vehicle.stepMs*100)}% walking speed</small></div><button className="button" disabled={!variety.shopOpen||me.coins<vehicle.price||me.ownedVehicles?.includes(vehicle.id)} onClick={()=>onAction({kind:'buyVehicle',vehicleId:vehicle.id})}>{me.ownedVehicles?.includes(vehicle.id)?'Owned':'Buy · ₽'+vehicle.price}</button></div>)}</div></div>;
  if(tab==='nursery')return <div className="variety-panel"><p>Pair two healthy level-5 companions. Nursery care costs ₽120. They stay with you, and the egg hatches after 32 steps.</p>{me.egg?<div className="egg-card"><strong>Egg of {me.egg.profile.name}</strong><p>{me.egg.parentNames.join(' + ')}</p><progress max={32} value={32-Math.max(0,me.egg.hatchAtStep-me.steps)}/><p>{Math.max(0,me.egg.hatchAtStep-me.steps)} steps until hatching</p></div>:<><label className="field">First parent<select value={a} onChange={e=>setA(e.target.value)}><option value="">Choose a companion</option>{all.map(c=><option key={c.id} value={c.id} disabled={c.level<5||c.hp<=0||(c.breedAfterStep??0)>me.steps}>{creatureInfo(c).name} · Lv{c.level}{(c.breedAfterStep??0)>me.steps?' · resting':''}</option>)}</select></label><label className="field">Second parent<select value={b} onChange={e=>setB(e.target.value)}><option value="">Choose a companion</option>{all.map(c=><option key={c.id} value={c.id} disabled={c.level<5||c.hp<=0||(c.breedAfterStep??0)>me.steps}>{creatureInfo(c).name} · Lv{c.level}{(c.breedAfterStep??0)>me.steps?' · resting':''}</option>)}</select></label><button className="button primary" disabled={!variety.nurseryOpen||!a||!b||a===b||me.coins<120} onClick={()=>onAction({kind:'breed',parentA:a,parentB:b})}>Pair companions · ₽120</button></>}<p className="small-copy">{variety.nurseryOpen?'Parents need 64 steps of rest between eggs.':'Visit the nursery keeper inside a shelter to arrange an egg.'} Hybrids inherit appearance, types, and traits. Hatched companions do not count as wild captures.</p></div>;
  if(tab==='records'){const metrics=[['captures','Captures'],['species','Species caught'],['maps','Maps explored'],['tiles','Tiles explored'],['trainers','Trainers defeated']] as const;const rows=[...variety.leaderboard].sort((a,b)=>b[metric]-a[metric]||a.name.localeCompare(b.name)||a.id.localeCompare(b.id));return <div className="variety-panel"><p>Records for this run. Captures exclude starters and eggs; species use stable identities. Trainer wins count each opponent once.</p><label className="field">Rank by<select value={metric} onChange={e=>setMetric(e.target.value as typeof metric)}>{metrics.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><ol className="leaderboard">{rows.map(player=><li key={player.id} className={player.id===me.id?'you':''}><span>{player.name}{player.id===me.id?' (you)':''}</span><strong>{player[metric]}</strong></li>)}</ol><p className="small-copy">Map blocks and individual ground tiles are separate records. Individual tile tracking starts with this update; recorded earlier captures and trainer victories are retained.</p></div>;}
  if(tab==='rides')return <div className="variety-panel"><p>Ride faster outdoors. Vehicles still respect walls, water, NPCs, and doors.</p>{variety.ownedVehicles.length?variety.ownedVehicles.map(vehicle=><div className="catalog-row" key={vehicle.id}><img src={vehicleImage(vehicle)} alt=""/><div><strong>{vehicle.name}</strong><p>{vehicle.description}</p></div><button className="button" disabled={!!me.sceneId&&me.vehicleId!==vehicle.id} onClick={()=>onAction({kind:'ride',vehicleId:me.vehicleId===vehicle.id?null:vehicle.id})}>{me.vehicleId===vehicle.id?'Dismount':'Ride'}</button></div>):<p>A shelter shopkeeper sells your first bicycle.</p>}{me.sceneId?<p className="small-copy">Your selected ride is parked while you are indoors.</p>:null}</div>;
  if(tab==='items')return <div className="variety-panel"><p className="wallet">Coins: ₽ {me.coins}</p><label className="field">Use item on<select value={targetIndex} onChange={e=>setTargetIndex(Number(e.target.value))}>{me.party.map((c,index)=><option key={c.id} value={index}>{creatureInfo(c).name} · {c.hp}/{c.maxHp} HP</option>)}</select></label><div className="catalog-list">{variety.inventoryItems.filter(item=>quantity(item.id)>0).map(item=><div className="catalog-row" key={item.id}><img src={itemImage(item)} alt=""/><div><strong>{item.name} ×{quantity(item.id)}</strong><p>{item.description}</p></div>{item.effect==='capture'?<small>Use in battle</small>:<button className="button" onClick={()=>onAction({kind:'useItem',itemId:item.id,index:targetIndex})}>Use</button>}</div>)}</div>{(me.repelSteps??0)>0?<p>Repel: {me.repelSteps} steps remaining</p>:null}</div>;
  const unique=[...new Map(all.map(c=>[creatureKey(c),c])).values()];return <div className="variety-panel"><p>{unique.length} owned species · {me.stats?.captures??0} wild captures. Original, generated, and hybrid species have separate identities.</p><div className="creature-codex">{unique.map(c=><article key={creatureKey(c)}><img src={creatureImage(c)} alt={creatureInfo(c).name}/><div><h3>{creatureInfo(c).name}</h3><p>{creatureInfo(c).types.join(' / ')} · {c.profile?.source??'classic'}</p><p>{c.profile?.description??'A familiar companion of the valley.'}</p><small>{(c.traits??[]).map(trait=>trait+': '+TRAITS[trait]).join(' · ')}</small></div></article>)}</div></div>;
}
